version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily", time: "04:00" }
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    labels: ["dependencies","github-actions"]
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "daily", time: "04:10" }
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    labels: ["dependencies","python"]
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "daily", time: "04:15" }
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    labels: ["dependencies","docker"]
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule: { interval: "daily", time: "04:16" }
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    labels: ["dependencies","docker-compose"]
    groups:
      all:
        patterns: ["*"]