version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "daily", time: "04:00" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "daily", time: "04:10" }
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]
    groups:
      py-minor-patch:
        applies-to: "version-updates"
        update-types: ["minor", "patch"]
        patterns: ["*"]
      py-security:
        applies-to: "security-updates"
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "daily", time: "04:15" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]
    groups:
      docker-images:
        patterns: ["*"]
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule: { interval: "daily", time: "04:16" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker-compose"]
    groups:
      compose:
        patterns: ["*"]